# CMake generated Testfile for 
# Source directory: /home/led/workspace/ceph_high_power_efficiency/src/test/mon
# Build directory: /home/led/workspace/ceph_high_power_efficiency/src/test/mon
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unittest_mon_moncap "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_mon_moncap")
set_tests_properties(unittest_mon_moncap PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;25;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;0;")
add_test(unittest_mon_monmap "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_mon_monmap")
set_tests_properties(unittest_mon_monmap PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;32;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;0;")
add_test(unittest_mon_pgmap "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_mon_pgmap")
set_tests_properties(unittest_mon_pgmap PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;40;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;0;")
add_test(unittest_mon_montypes "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_mon_montypes")
set_tests_properties(unittest_mon_montypes PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;47;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;0;")
add_test(unittest_mon_election "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_mon_election")
set_tests_properties(unittest_mon_election PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;82;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/mon/CMakeLists.txt;0;")
