# CMake generated Testfile for 
# Source directory: /home/led/workspace/ceph_high_power_efficiency/src/test/mgr
# Build directory: /home/led/workspace/ceph_high_power_efficiency/src/test/mgr
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unittest_mgr_mgrcap "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_mgr_mgrcap")
set_tests_properties(unittest_mgr_mgrcap PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/CMakeLists.txt;5;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/CMakeLists.txt;0;")
add_test(unittest_mgr_ttlcache "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_mgr_ttlcache")
set_tests_properties(unittest_mgr_ttlcache PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/CMakeLists.txt;10;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/CMakeLists.txt;0;")
add_test(mgr-dashboard-frontend-unittests "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/run-frontend-unittests.sh")
set_tests_properties(mgr-dashboard-frontend-unittests PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/CMakeLists.txt;17;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/CMakeLists.txt;0;")
add_test(mgr-dashboard-smoke.sh "/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/mgr-dashboard-smoke.sh")
set_tests_properties(mgr-dashboard-smoke.sh PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/CMakeLists.txt;20;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/mgr/CMakeLists.txt;0;")
