# CMake generated Testfile for 
# Source directory: /home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard
# Build directory: /home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(setup-venv-for-mgr-dashboard-py3 "/home/led/workspace/ceph_high_power_efficiency/src/tools/setup-virtualenv.sh" "--python=/usr/bin/python3.10" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-py3-virtualenv")
set_tests_properties(setup-venv-for-mgr-dashboard-py3 PROPERTIES  FIXTURES_SETUP "venv-for-mgr-dashboard-py3" WORKING_DIRECTORY "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;72;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;12;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(teardown-venv-for-mgr-dashboard-py3 "/usr/bin/cmake" "-E" "remove_directory" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-py3-virtualenv")
set_tests_properties(teardown-venv-for-mgr-dashboard-py3 PROPERTIES  FIXTURES_CLEANUP "venv-for-mgr-dashboard-py3" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;78;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;12;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(run-tox-mgr-dashboard-py3 "/home/led/workspace/ceph_high_power_efficiency/src/script/run_tox.sh" "--source-dir" "/home/led/workspace/ceph_high_power_efficiency" "--build-dir" "/home/led/workspace/ceph_high_power_efficiency" "--tox-path" "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard" "--tox-envs" "py3" "--venv-path" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-py3-virtualenv")
set_tests_properties(run-tox-mgr-dashboard-py3 PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/src/pybind" FIXTURES_REQUIRED "venv-for-mgr-dashboard-py3" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;83;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;12;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(setup-venv-for-mgr-dashboard-lint "/home/led/workspace/ceph_high_power_efficiency/src/tools/setup-virtualenv.sh" "--python=/usr/bin/python3.10" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-lint-virtualenv")
set_tests_properties(setup-venv-for-mgr-dashboard-lint PROPERTIES  FIXTURES_SETUP "venv-for-mgr-dashboard-lint" WORKING_DIRECTORY "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;72;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;13;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(teardown-venv-for-mgr-dashboard-lint "/usr/bin/cmake" "-E" "remove_directory" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-lint-virtualenv")
set_tests_properties(teardown-venv-for-mgr-dashboard-lint PROPERTIES  FIXTURES_CLEANUP "venv-for-mgr-dashboard-lint" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;78;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;13;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(run-tox-mgr-dashboard-lint "/home/led/workspace/ceph_high_power_efficiency/src/script/run_tox.sh" "--source-dir" "/home/led/workspace/ceph_high_power_efficiency" "--build-dir" "/home/led/workspace/ceph_high_power_efficiency" "--tox-path" "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard" "--tox-envs" "lint" "--venv-path" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-lint-virtualenv")
set_tests_properties(run-tox-mgr-dashboard-lint PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/src/pybind" FIXTURES_REQUIRED "venv-for-mgr-dashboard-lint" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;83;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;13;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(setup-venv-for-mgr-dashboard-check "/home/led/workspace/ceph_high_power_efficiency/src/tools/setup-virtualenv.sh" "--python=/usr/bin/python3.10" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-check-virtualenv")
set_tests_properties(setup-venv-for-mgr-dashboard-check PROPERTIES  FIXTURES_SETUP "venv-for-mgr-dashboard-check" WORKING_DIRECTORY "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;72;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;14;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(teardown-venv-for-mgr-dashboard-check "/usr/bin/cmake" "-E" "remove_directory" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-check-virtualenv")
set_tests_properties(teardown-venv-for-mgr-dashboard-check PROPERTIES  FIXTURES_CLEANUP "venv-for-mgr-dashboard-check" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;78;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;14;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(run-tox-mgr-dashboard-check "/home/led/workspace/ceph_high_power_efficiency/src/script/run_tox.sh" "--source-dir" "/home/led/workspace/ceph_high_power_efficiency" "--build-dir" "/home/led/workspace/ceph_high_power_efficiency" "--tox-path" "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard" "--tox-envs" "check" "--venv-path" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-check-virtualenv")
set_tests_properties(run-tox-mgr-dashboard-check PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/src/pybind" FIXTURES_REQUIRED "venv-for-mgr-dashboard-check" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;83;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;14;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(setup-venv-for-mgr-dashboard-openapi "/home/led/workspace/ceph_high_power_efficiency/src/tools/setup-virtualenv.sh" "--python=/usr/bin/python3.10" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-openapi-virtualenv")
set_tests_properties(setup-venv-for-mgr-dashboard-openapi PROPERTIES  FIXTURES_SETUP "venv-for-mgr-dashboard-openapi" WORKING_DIRECTORY "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;72;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;15;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(teardown-venv-for-mgr-dashboard-openapi "/usr/bin/cmake" "-E" "remove_directory" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-openapi-virtualenv")
set_tests_properties(teardown-venv-for-mgr-dashboard-openapi PROPERTIES  FIXTURES_CLEANUP "venv-for-mgr-dashboard-openapi" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;78;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;15;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
add_test(run-tox-mgr-dashboard-openapi "/home/led/workspace/ceph_high_power_efficiency/src/script/run_tox.sh" "--source-dir" "/home/led/workspace/ceph_high_power_efficiency" "--build-dir" "/home/led/workspace/ceph_high_power_efficiency" "--tox-path" "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard" "--tox-envs" "openapi-check" "--venv-path" "/home/led/workspace/ceph_high_power_efficiency/mgr-dashboard-openapi-virtualenv")
set_tests_properties(run-tox-mgr-dashboard-openapi PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/home/led/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/src/pybind" FIXTURES_REQUIRED "venv-for-mgr-dashboard-openapi" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;83;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;15;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/dashboard/CMakeLists.txt;0;")
subdirs("frontend")
