# CMake generated Testfile for 
# Source directory: /home/led/workspace/ceph_high_power_efficiency/src/test/encoding
# Build directory: /home/led/workspace/ceph_high_power_efficiency/src/test/encoding
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(check-generated.sh "/home/led/workspace/ceph_high_power_efficiency/src/test/encoding/check-generated.sh")
set_tests_properties(check-generated.sh PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/src/test/encoding/CMakeLists.txt;2;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/encoding/CMakeLists.txt;0;")
add_test(readable.sh "/home/led/workspace/ceph_high_power_efficiency/src/test/encoding/readable.sh")
set_tests_properties(readable.sh PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/src/test/encoding/CMakeLists.txt;3;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/encoding/CMakeLists.txt;0;")
