# CMake generated Testfile for 
# Source directory: /home/led/workspace/ceph_high_power_efficiency/src/test/crush
# Build directory: /home/led/workspace/ceph_high_power_efficiency/src/test/crush
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unittest_crush_wrapper "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_crush_wrapper")
set_tests_properties(unittest_crush_wrapper PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/crush/CMakeLists.txt;4;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/crush/CMakeLists.txt;0;")
add_test(unittest_crush "/home/led/workspace/ceph_high_power_efficiency/bin/unittest_crush")
set_tests_properties(unittest_crush PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;53;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/crush/CMakeLists.txt;10;add_ceph_unittest;/home/led/workspace/ceph_high_power_efficiency/src/test/crush/CMakeLists.txt;0;")
add_test(crush_weights.sh "/home/led/workspace/ceph_high_power_efficiency/src/test/crush/crush_weights.sh")
set_tests_properties(crush_weights.sh PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_DIR=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/lib/cython_modules/lib.3:/home/led/workspace/ceph_high_power_efficiency/src/pybind;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency" TIMEOUT "3600" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;5;add_test;/home/led/workspace/ceph_high_power_efficiency/src/test/crush/CMakeLists.txt;13;add_ceph_test;/home/led/workspace/ceph_high_power_efficiency/src/test/crush/CMakeLists.txt;0;")
