# CMake generated Testfile for 
# Source directory: /home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr
# Build directory: /home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(setup-venv-for-mgr "/home/led/workspace/ceph_high_power_efficiency/src/tools/setup-virtualenv.sh" "--python=/usr/bin/python3.10" "/home/led/workspace/ceph_high_power_efficiency/mgr-virtualenv")
set_tests_properties(setup-venv-for-mgr PROPERTIES  FIXTURES_SETUP "venv-for-mgr" WORKING_DIRECTORY "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;72;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/CMakeLists.txt;16;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/CMakeLists.txt;0;")
add_test(teardown-venv-for-mgr "/usr/bin/cmake" "-E" "remove_directory" "/home/led/workspace/ceph_high_power_efficiency/mgr-virtualenv")
set_tests_properties(teardown-venv-for-mgr PROPERTIES  FIXTURES_CLEANUP "venv-for-mgr" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;78;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/CMakeLists.txt;16;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/CMakeLists.txt;0;")
add_test(run-tox-mgr "/home/led/workspace/ceph_high_power_efficiency/src/script/run_tox.sh" "--source-dir" "/home/led/workspace/ceph_high_power_efficiency" "--build-dir" "/home/led/workspace/ceph_high_power_efficiency" "--tox-path" "/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr" "--tox-envs" "py3,py37,mypy,flake8,jinjalint,nooptional" "--venv-path" "/home/led/workspace/ceph_high_power_efficiency/mgr-virtualenv")
set_tests_properties(run-tox-mgr PROPERTIES  ENVIRONMENT "CEPH_ROOT=/home/led/workspace/ceph_high_power_efficiency;CEPH_BIN=/home/led/workspace/ceph_high_power_efficiency/bin;CEPH_LIB=/home/led/workspace/ceph_high_power_efficiency/lib;CEPH_BUILD_VIRTUALENV=/home/led/workspace/ceph_high_power_efficiency;LD_LIBRARY_PATH=/home/led/workspace/ceph_high_power_efficiency/lib;PATH=/home/led/workspace/ceph_high_power_efficiency/bin:/home/led/workspace/ceph_high_power_efficiency/src:/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr:/home/led/.vscode-server/cli/servers/Stable-17baf841131aa23349f217ca7c570c76ee87b957/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/led/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand;PYTHONPATH=/home/led/workspace/ceph_high_power_efficiency/src/pybind" FIXTURES_REQUIRED "venv-for-mgr" _BACKTRACE_TRIPLES "/home/led/workspace/ceph_high_power_efficiency/cmake/modules/AddCephTest.cmake;83;add_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/CMakeLists.txt;16;add_tox_test;/home/led/workspace/ceph_high_power_efficiency/src/pybind/mgr/CMakeLists.txt;0;")
subdirs("dashboard")
subdirs("rook")
